### ISSUE TITLE
Vertical Lines Across the Screen when moving horizontally

### ISSUE THREAD

**Issue by Ramonnn** [NimbusNiles/RogueDixie#16]

**Comment by NimbusNiles** [comment]
Related to Issue #12, this is not happening on my (Niels) screen. Needs further research in camera-pixel and map tile pixel allignment.

**Comment by NimbusNiles** [comment]
It is again happening at my screen again. Maybe the solution is to make sure the camera position is limited to 1/32s of a tile position.

**Comment by TimmPure** [comment]
Possible solution in changing camera size? 
http://answers.unity3d.com/questions/855458/flickering-lines-when-moving-cameraunity-2d.html

Or rounding camPos to nearest offset position?
http://answers.unity3d.com/questions/807968/flickering-seams-when-moving-camera-unity2d.html

**Comment by TimmPure** [comment]
Maybe if (modulo .5 on the camera transform.x position = 0), add 1/64th is a better solution (less camera jitter).
