### ISSUE TITLE
Player object is called after death (not possible)

### ISSUE THREAD

**Issue by Ramonnn** [NimbusNiles/RogueDixie#18]
After death, player and all his components are being hailed but cannot be accessed because player game-object is destroyed. Infinite error loop (due to Update?)

**Comment by TimmPure** [comment]
Known issue from commit https://github.com/NimbusNiles/RogueDixie/commit/3966220b8d47a7f6d3b0d5d35e22cfa5e90e550d

**Comment by NimbusNiles** [comment]
This is solved by not destroying the player, but instead showing a Wasted screen overlay. This enables a future revive option by teammates
